### ISSUE TITLE
Port for nut server access?

### ISSUE THREAD

**Issue by lotekjunky** [krptg0/doge#3]
First of all, good job on this! I tried to add another -p port forward to send 9000 to the docker, but it doesn't appear to be working. Which port is the internal nut server using so I can use my nut client with this docker image?

edit: NEVERMIND! Port 9000 is it... I hadn't properly restarted the container for the new port forward to kick in.

**Comment by krptg0** [comment]
Feel free to close such issues is resolved on their own :) Thanks for the compliment !
